import type { PropertyResponse } from '@/lib/types/property';

export const mockProperties: PropertyResponse[] = [
  {
    id: '1',
    ownerId: 'user-123',
    title: 'Apartamento Luxuoso no Talatona',
    description: 'Apartamento moderno com vista para o mar, localizado no coração de Talatona.',
    tipo: 'Apartamento',
    status: 'para comprar',
    rotulo: 'À Venda',
    price: 35000000,
    unidade_preco: 'KZ',
    preco_antes: 37000000,
    preco_depois: 34000000,
    preco_chamada: 'Preço Negociável',
    caracteristicas: ['Ar Condicionado', 'Piscina', 'TV a Cabo', 'WiFi'],
    size: '120',
    area_terreno: 200,
    bedrooms: 3,
    bathrooms: 2,
    garagens: 1,
    garagemtamanho: '15',
    anoconstrucao: 2020,
    propertyid: 'APTLT-001',
    detalhesadicionais: [
      { titulo: 'Condomínio fechado', valor: 'Sim' },
      { titulo: 'Andar', valor: '5º' },
    ],
    endereco: 'Rua da Independência',
    bairro: 'Talatona',
    cidade: 'Talatona',
    provincia: 'Luanda',
    pais: 'Angola',
    notaprivada: 'Cliente VIP, atenção especial',
    gallery: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
      'https://images.unsplash.com/photo-1600585154206-6c755b6ff711'
    ],
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c'
  },
  {
    id: '2',
    ownerId: 'user-456',
    title: 'Vivenda Moderna em Benfica',
    description: 'Vivenda com quintal, ideal para famílias grandes, próxima a escolas.',
    tipo: 'Vivenda',
    status: 'para alugar',
    rotulo: 'Promoção',
    price: 250000,
    unidade_preco: 'KZ/mês',
    preco_antes: 300000,
    preco_depois: 240000,
    preco_chamada: 'Inclui internet e água',
    caracteristicas: ['Ar Condicionado', 'WiFi', 'Lavanderia', 'Máquina de Lavar'],
    size: '180',
    area_terreno: 500,
    bedrooms: 4,
    bathrooms: 3,
    garagens: 2,
    garagemtamanho: '30',
    anoconstrucao: 2015,
    propertyid: 'VDBFC-002',
    detalhesadicionais: [
      { titulo: 'Jardim', valor: 'Sim' },
      { titulo: 'Câmeras de Segurança', valor: 'Instaladas' },
    ],
    endereco: 'Rua da Paz',
    bairro: 'Benfica',
    cidade: 'Luanda',
    provincia: 'Luanda',
    pais: 'Angola',
    notaprivada: '',
    gallery: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914',
      'https://images.unsplash.com/photo-1600607682511-cf7b6c4f231b'
    ],
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914'
  },
  {
    id: '3',
    ownerId: 'user-789',
    title: 'Terreno para Investimento no Patriota',
    description: 'Terreno plano com acesso asfaltado, ideal para construção de condomínio.',
    tipo: 'Terreno',
    status: 'para comprar',
    rotulo: 'À Venda',
    price: 9000000,
    unidade_preco: 'KZ',
    preco_antes: undefined,
    preco_depois: undefined,
    preco_chamada: 'Preço fechado',
    caracteristicas: [],
    size: '',
    area_terreno: 1200,
    bedrooms: 0,
    bathrooms: 0,
    garagens: 0,
    garagemtamanho: '',
    anoconstrucao: undefined,
    propertyid: 'TRPAT-003',
    detalhesadicionais: [
      { titulo: 'Documentação', valor: 'Regularizada' },
      { titulo: 'Acesso', valor: 'Asfaltado' }
    ],
    endereco: 'Via Expressa',
    bairro: 'Patriota',
    cidade: 'Luanda',
    provincia: 'Luanda',
    pais: 'Angola',
    notaprivada: 'Terreno herdado, venda urgente',
    gallery: [
      'https://images.unsplash.com/photo-1550581190-9c1c48d21d6c'
    ],
    image: 'https://images.unsplash.com/photo-1550581190-9c1c48d21d6c'
  }
];
