export type Property = {
  id: string;
  image: string;
  gallery?: string[];
  title: string;
  description?: string;
  location: string;
  endereco?: string;
  bairro?: string;
  cidade?: string;
  provincia?: string;
  pais?: string;
  tipo?: string;
  status: 'para alugar' | 'para comprar';
  rotulo?: string;
  price: string | null;
  unidadepreco?: string;
  precoantes?: string | null;
  precodepois?: string | null;
  precochamada?: string;
  caracteristicas?: string[];
  size: string;
  areaterreno?: number;
  bedrooms: number;
  bathrooms?: number;
  garagens?: number;
  garagemtamanho?: string;
  anoconstrucao?: string;
  propertyid?: string;
  detalhesadicionais?: { titulo: string; valor: string }[];
  anexos?: string[];
  video?: string;
  imagem360?: string;
  planoschao?: boolean;
  notaprivada?: string;
  owner_id?: string;
  created_at?: string;
};
